COURSE_ACTS(COURSE_BOB, _(" 1 CAMP DE BATALLA BOB-OMB"),
       _("GRAN BOB-OMB AL CIM")     , _("LA CURSA AMB KOOPA EL RÀPID") , _("LLENÇA'T A L'ILLA AL CEL"),
       _("EN CERCA DE LES 8 MONEDES ROJES")          , _("MARIO, A VOLAR!")        , _("ALLIBERA EN CHOMP CADENES"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTALESA D'EN WHOMP"),
       _("DERROCA EN WHOMP")        , _("AL MÉS ALT DE LA FORTALESA")    , _("LLENÇA'T CONTRA EL GRAN CEL"),
       _("MONEDES ROJES A LES ILLES FLOTANTS"), _("CAIGUDA LLIURE A L'ILLA DE LA GÀBIA")    , _("A CANONADES CONTRA EL MUR"))

COURSE_ACTS(COURSE_JRB, _(" 3 BADIA DEL CAPITÀ"),
       _("EL BOTÍ DEL VAIXELL ENFONSAT")    , _("POT L'ANGUILA SORTIR A JUGAR?") , _("TRESOR A LA COVA DE L'OCEÀ"),
       _("MONEDES ROJES AL VAIXELL FLOTANT")  , _("APUNTA AL MÉS ALT DE L'AGULLA")     , _("A CONTRACORRENT"))

COURSE_ACTS(COURSE_CCM, _(" 4 GÈLIDA, GÈLIDA MUNTANYA"),
       _("LLISCA LLISCANT PEL TOBOGAN")             , _("PETIT PINGÜÍ PERDUT")             , _("EL MÉS RÀPID DEL GEL"),
       _("LA GÈLIDA BAIXADA DE LES 8 MONEDES ROJES")  , _("NINOT DE NEU SENSE CAP")       , _("BOTA I REBOTA A LA PARET"))

COURSE_ACTS(COURSE_BBH, _(" 5 MANSIÓ DELS BOO"),
       _("CAÇAFANTASMES")            , _("EL CARRUSSEL DEL GRAN BOO") , _("EL SECRET DELS LLIBRES ENCANTATS"),
       _("CERCA LES ESGARRIFOSES 8 MONEDES ROJES")          , _("EL BALCÓ DEL GRAN BOO")             , _("HABITACIÓ SECRETA AMB CARA I ULLS"))

COURSE_ACTS(COURSE_HMC, _(" 6 COVA DEL LABERINT"),
       _("EL MONSTRE DE LA COVA DEL LLAC")  , _("ELEVA'T PER LES 8 MONEDES ROJES")       , _("MARIO, L'HOME D'ACER!"),
       _("NAVEGANT EL LABERINT TÒXIC")     , _("L'ALTRA SORTIDA DEL LABERINT")     , _("COMPTE AMB LES BOLES DE ROCA!"))

COURSE_ACTS(COURSE_LLL, _(" 7 TERRA DE LA LAVA"),
       _("BULL EL GRAN BULLY")            , _("A LA CAÇA DELS BULLY'S")             , _("EL PUZLE DE LES 8 MONEDES ROJES"),
       _("EL TRONC INCANDESCENT")           , _("AL BELL COR DEL VOLCÀ")  , _("LA PLATAFORMA VOLADORA DEL VOLCÀ"))

COURSE_ACTS(COURSE_SSL, _(" 8 TERRA DE LA SORRA MOVEDISSA"),
       _("A LES URPES DE LA GRAN AU") , _("A MÉS ALT DE LA PIRÀMIDE")      , _("EL SECRET DE LA PIRÀMIDE"),
       _("CORONA ELS QUATRE PILARS"), _("VOLA LLIURE A PER LES 8 MONEDES ROJES")   , _("EL LABERINT DE LA PIRÀMIDE"))

COURSE_ACTS(COURSE_DDD, _(" 9 GRAN, GRAN MOLL"),
       _("SOBRE EL SUBMARÍ D'EN BOWSER")            , _("A COFRE-CORRENT")         , _("8 MONEDES ROJES DE PAL EN PAL"),
       _("ATRAVESSANT EL CORRENT")        , _("RERE L'ESTELA DE LA MANTA")        , _("COL.LECCIONA ELS BARRETS!"))

COURSE_ACTS(COURSE_SL, _("10 PAÍS DEL NINOT DE NEU"),
       _("SOBRE EL CAP DEL NINOT DE NEU")            , _("REFRESCA EL BULLY")          , _("DINS DEL GLAÇÓ"),
       _("REMOLÍ DE L'ESTANY GELAT")  , _("SURFEJANT PER LES 8 MONEDES ROJES") , _("A L'IGLÚ"))

COURSE_ACTS(COURSE_WDW, _("11 VILA MOLLA-SECA"),
       _("MULLANT PLATAFORMES!")         , _("AL MÉS ALT DE LA VILA")               , _("SECRETS A LES TORRES I AL CEL"),
       _("ASCENSOR EXPRÉS: AFANYA'T!")   , _("LES 8 MONEDES ROJES DE LA VILA")      , _("CURSA RÀPIDA PER LA VILA!"))

COURSE_ACTS(COURSE_TTM, _("12 MUNTANYA BEN, BEN ALTA"),
       _("ESCALA LA MUNTANYA")            , _("EL MISTERI DE LA GÀBIA DEL MICO")    , _("8 MONEDES ROJES A XAMPINYONS ROJOS"),
       _("EL MISTERIÓS COSTAT DE LA MUNTANYA")       , _("LA IMPRESSIONANT VISTA DES DEL PONT") , _("DISPARAT AL XAMPINYÓ SOLITARI"))

COURSE_ACTS(COURSE_THI, _("13 PETITA GRAN ILLA"),
       _("SENSE POR CONTRA LES PLANTES PIRANYA")      , _("AL CIM DE L'ILLA GEGANT"), _("REVENJA AMB KOOPA EL RÀPID"),
       _("ELS CINC PETITS SECRETS DE L'ILLA")       , _("LES 8 MONEDES ROJES DE NA FLORUGA")           , _("BATALLA DINS LA MUNTANYA! FLOREIX NA FLORUGA"))

COURSE_ACTS(COURSE_TTC, _("14 RELLOTGE TIC-TAC"),
       _("ENGÀBIA'T A LA GÀBIA!")            , _("LA FOSA I ELS PÈNDULS")     , _("UN COP DE MÀ"),
       _("PICA LA ROCA PICUDA")           , _("SALTS TEMPORITZATS SOBRE BARRES MÒBILS")    , _("ATURA EL TEMPS PER 8 MONEDES ROJES"))

COURSE_ACTS(COURSE_RR, _("15 SENDA ARC DE SANT MARTÍ"),
       _("CREUER DEL SANT MARTÍ")  , _("LA MANSIÓ CELESTIAL")      , _("LES 8 MONEDES ROJES DEL LABERINT VERTICAL"),
       _("GRONXANT-SE A LA BRISA")        , _("EL TRUC DE LES PIRÀMIDES")             , _("ALGUN LLOC SOBRE L'ARC DE SANT MARTÍ"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER A LES TENEBRES"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER AL MAR DE FOC"))
SECRET_STAR(COURSE_BITS, _("   BOWSER AL CEL"))
SECRET_STAR(COURSE_PSS, _("   EL TOBOGAN SECRET DE LA PRINCESA"))
SECRET_STAR(COURSE_COTMC, _("   CAVERNA OF DEL BARRET DE METALL"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DEL BARRET ALAT"))
SECRET_STAR(COURSE_VCUTM, _("   BARRET TRANSLÚCID SOTA EL FOSSAR"))
SECRET_STAR(COURSE_WMOTR, _("   MARIO VOLADOR SOBRE L'ARC DE SANT MARTÍ"))
SECRET_STAR(COURSE_SA, _("   L'AQUARI SECRET"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   ESTRELLES SECRETES DEL CASTELL"))

EXTRA_TEXT(0, _("UNA DE LES ESTRELLES SECRETES DEL CASTELL!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
